alert('Cереднє арифметичне із трьох чисел:')
let First=prompt(`Введіть число`)
let Second=prompt(`Введіть число`)
let Third=prompt(`Введіть число`)
let am=(+First + +Second + +Third)
alert(`Cереднє арифметичне ${am / 3}`)